CREATE TABLE IF NOT EXISTS account_transaction (
    id INTEGER,
    account_num CHARACTER VARYING,
    amount FLOAT,
    transaction_type CHARACTER VARYING,
    balance FLOAT,
    sms_id uuid,
    user_id CHARACTER VARYING,
    transaction_time TIMESTAMP,
    extra_info CHARACTER VARYING,
    source CHARACTER VARYING,
    created_ts TIMESTAMP,
    last_updated_ts TIMESTAMP,
    transaction_mode CHARACTER VARYING,
    beneficiary CHARACTER VARYING,
    expense_category CHARACTER VARYING,
    document_id INTEGER,
    is_expense BOOLEAN,
    client_id INTEGER,
    notes CHARACTER VARYING,
    sync_type CHARACTER VARYING,
    bank CHARACTER VARYING,
    devices_synced CHARACTER VARYING,
    status CHARACTER VARYING
);
